pipeline {
    agent {
        dockerfile {
            dir 'automation'
            reuseNode true
        }
    }

    stages {
        stage('Rust Toolchain Info') {
          steps {
            sh 'rustc --version'
          }
        }
        stage('Clippy') {
          steps {
            sh 'cargo clippy --target thumbv7em-none-eabihf'
          }
        }
        stage('Rustfmt') {
          steps {
            sh 'cargo fmt'
          }
        }
        stage('Docs') {
          steps {
            sh """
              RUSTDOCFLAGS="--cfg docsrs --generate-link-to-definition -Z unstable-options" cargo +nightly doc -p vorago-peb1
              RUSTDOCFLAGS="--cfg docsrs --generate-link-to-definition -Z unstable-options" cargo +nightly doc -p va416xx-hal --features va41630
              RUSTDOCFLAGS="--cfg docsrs --generate-link-to-definition -Z unstable-options" cargo +nightly doc -p va416xx
            """
          }
        }
        stage('Check') {
          steps {
            sh 'cargo check --target thumbv7em-none-eabihf'
          }
        }
        stage('Check Examples') {
          steps {
            sh """
              cargo check --target thumbv7em-none-eabihf --examples
            """
          }
        }
    }
}
